<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ReactiveHMI.ReactiveInterface.TemplateRepositories</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\M2M\M2MCommunication.Core\M2MCommunication.Core.csproj" />
    <ProjectReference Include="..\..\M2M\M2MCommunication.Services\M2MCommunication.Services.csproj" />
  </ItemGroup>

</Project>
